version: "2"
services:
  formatmoney:
    image: formatmoney:t1
    container_name: app1
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
        - "7338:7338"
    command: mvn spring-boot:run